//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TangaDummy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building
    {
        public long BuildingID { get; set; }
        public Nullable<long> LandRefNo { get; set; }
        public string BuildingType { get; set; }
        public string BuildingName { get; set; }
        public string BuildingAddress { get; set; }
        public long BuildingOwner { get; set; }
        public Nullable<int> BuildingFloors { get; set; }
        public Nullable<bool> PaymentStatus { get; set; }
        public Nullable<decimal> Arrears { get; set; }
    
        public virtual PersonTable PersonTable { get; set; }
    }
}
