//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TangaDummy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Tanga_City_CouncilEntities : DbContext
    {
        public Tanga_City_CouncilEntities()
            : base("name=Tanga_City_CouncilEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Building> Buildings { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PermitType> PermitTypes { get; set; }
        public virtual DbSet<PersonTable> PersonTables { get; set; }
        public virtual DbSet<PersonWallet> PersonWallets { get; set; }
        public virtual DbSet<ConfirmedPayment> ConfirmedPayments { get; set; }
        public virtual DbSet<PaymentTrailMessage> PaymentTrailMessages { get; set; }
        public virtual DbSet<WaterMeter> WaterMeters { get; set; }
    }
}
