//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TangaDummy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public long PaymentID { get; set; }
        public Nullable<decimal> PaymentMade { get; set; }
        public long PersonID { get; set; }
        public Nullable<long> PermitType { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string PaymentReference { get; set; }
    
        public virtual PermitType PermitType1 { get; set; }
        public virtual PersonTable PersonTable { get; set; }
    }
}
