//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TangaDummy
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentTrailMessage
    {
        public long OnlinePaymentTrailID { get; set; }
        public string MerchantRequestID { get; set; }
        public string CheckoutRequestID { get; set; }
        public string ResponseCode { get; set; }
        public string CustomerMessage { get; set; }
        public string ResponseDescription { get; set; }
        public string IDNumber { get; set; }
        public System.DateTime PaymentStamp { get; set; }
    
        public virtual PaymentTrailMessage PaymentTrailMessages1 { get; set; }
        public virtual PaymentTrailMessage PaymentTrailMessage1 { get; set; }
    }
}
