//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TangaDummy
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonTable()
        {
            this.Buildings = new HashSet<Building>();
            this.PersonWallets = new HashSet<PersonWallet>();
            this.Payments = new HashSet<Payment>();
            this.WaterMeters = new HashSet<WaterMeter>();
        }
    
        public long PersonID { get; set; }
        public string Person_Name { get; set; }
        public Nullable<System.DateTime> Date_of_Birth { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string IDNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Building> Buildings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonWallet> PersonWallets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WaterMeter> WaterMeters { get; set; }
    }
}
