//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TangaDummy
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonWallet
    {
        public long WalletID { get; set; }
        public Nullable<long> PersonID { get; set; }
        public Nullable<decimal> CurrentAmount { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    
        public virtual PersonTable PersonTable { get; set; }
    }
}
