//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TangaDummy
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaterMeter
    {
        public long MeterID { get; set; }
        public string MeterNo { get; set; }
        public string Meter_Status { get; set; }
        public string BillName { get; set; }
        public string Brand { get; set; }
        public long MeterOwner { get; set; }
        public string Ward { get; set; }
        public string Street { get; set; }
        public Nullable<decimal> Arrears { get; set; }
        public string Meter_Account_No { get; set; }
    
        public virtual PersonTable PersonTable { get; set; }
    }
}
